version: '3'

networks:
  tutorial:
    name: tutorial

services:
  mongodb1:
    image: mongo:4.2.24-bionic
    networks:
      - tutorial
    ports:
      - target: 27017
        published: 27017
    command: mongod --replSet cluster

  mongodb2:
    image: mongo:4.2.24-bionic
    networks:
      - tutorial
    ports:
      - target: 27017
        published: 27018
    command: mongod --replSet cluster
    depends_on:
      - mongodb1

  mongo_express:
    image: mongo-express
    networks:
      - tutorial
    ports:
      - target: 8081
        published: 8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb1
    command: /bin/bash -c "sleep 60 && /docker-entrypoint.sh mongo-express"
    depends_on:
      - mongodb1
      - mongodb2
